### ISSUE TITLE
SDW Client: Read/Unread re-explorations

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-ux#107]
— creating ticket to create it, will populate later —

**Comment by eloquence** [comment]
Hey @ninavizz, this is empty and seems duplicative of #106, do we need it?

**Comment by ninavizz** [comment]
Whoops, now I remember you having created the other one! Thx for that, and my bad on this redundant issue. (thx for grooming this backlog, on an aside!)
