### ISSUE TITLE
Update All Source UI Messaging Styles/Text

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-ux#112]
## Problem
`1.0.0` introduced a new visual style to the SD Web UIs, and many usability improvements. In keeping with this, an audit needs to be done against all messaging, and once completed, those messaging style/text/class updates need to be implemented.

## Solution
_Below is to be listed each of the SUI templates w/ a flash message on them, shown abreast a UX solution (Zeplin) along with how this message should be classed. Tor messaging not included, as its messaging changes more often._

**Page** | **Message Ask** | **Class** | **Mockup** | **Art** 
--- | --- | --- | --- | ---
Login | Codename Fail | Action Bang | _—tbd—_ | _—tbd—_
Submit | Submit Fail | Action Bang | _—tbd—_ | _—tbd—_
Submit | Submission successful | Confirm | _—tbd—_ | _—tbd—_
Submit | You got mail! | ?? | _—tbd—_ | _—tbd—_
Submit | Reply deleted | Confirm | _—tbd—_ | _—tbd—_
Submit | Entropy Fail | Info | _—tbd—_ | _—tbd—_
Anything? | Bueller? | McFly? | _—tbd—_ | _—tbd—_

**Comment by eloquence** [comment]
Transferred from SecureDrop Core to UX repo, let's consider in the context of future work on Source UI.

**Comment by ninavizz** [comment]
Redundant with #88
