### ISSUE TITLE
How to highlight a selected source

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-ux#115]
## Description

> When there are _Sources_ populating the _Source List_ container, each un-selected _Source_ has a background color of #FFF @ 100%. 
> - When selected, that should be #FFF @ 0%. 
> - On _Empty_ mode, however, the _Source List_  container should have one giant block of #FFF @ 40% in it, with the fadie-lines implying slots for non-existing _Sources_. 
>    - I may need to create art for the latter, for you. 
> 

_Originally posted by @ninavizz in https://github.com/freedomofpress/securedrop-client/issues/512#issuecomment-517543942_ which was part of an issue closed during backlog grooming.

## Things that need discussion

* What are our most up-to-date zeplin screens? Could we link to them here?
* What does this look like when there is a scrollbar on the right of the source list? 
* Are there other things we can do that makes it more obvious which source is selected when displaying a conversation?

**Comment by ninavizz** [comment]
Note: Visibility of selected items coming through a windowshade from modal dialogs, will be important in resolving this.

**Comment by ninavizz** [comment]
I believe this was solved for some time ago, so am closing—Allie, feel free to ping me on Signal, if you have questions!
