### ISSUE TITLE
Need to recruit non-customer users for testing

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-ux#2]
Nina and Eric to work on creating a survey page, with introductory text and an image at the top. @eloquence to reach-out to orgs such as INN to request blasting in newsletters and over social media channels.

* [In-progress GDoc](https://docs.google.com/document/d/1uSYD36Ehh3dq4p13XcHw6DC5jmelAQdrwtpPfCLPI1E/edit?usp=sharing)
* Page to live on securedrop.org
  * TBD contributor to eliminate domain-dependent red OMGWTF box for privacy disclosure
  * Erik likely to code survey
  * Nina TBD on image at top (would love help with that, if anyone has ideas!)

**Comment by ninavizz** [comment]
cc'ing @eloquence and @redshiftzero to get this on their radar

**Comment by ninavizz** [comment]
@eloquence An additional method to extend our reach and could get us some traction w/o depending on newsletter cycles, would be asking INN and other journalist orgs to share our ask via Twitter and Facecrack. Having it Tweeted from the FOP acct could potentially help, too.

**Comment by eloquence** [comment]
Closing this issue since it describes work that is now done, let's file separate issues for specific additional outreach efforts (e.g., to under-represented groups).
