### ISSUE TITLE
Newsroom Journey Map(s)

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-ux#21]
What does it take to install, launch, and maintain a SecureDrop instance? 
What is the broader workflow of an investigative team, and how does SecureDrop fit into that? 
How are folks trained in OpeSec to both use SecureDrop and other security tools—and what gaps remain between what we've thought to teach them, and what they actually need to learn to conduct their work in the safest fashion possible?
When do folks need support, what do they need support for, and how smoothly are those needs met? 
Is there a pipeline between support and product to keep unmet user needs on the FPF radar?
What are unmet needs of Journalists, Admins, and Newsroom Maintainers?

**Comment by ninavizz** [comment]
Discovery research by @ei8fdb to influence early design stuff on Workstation, yet to be synthesized. Will quickly do, and post here upon completion.

**Comment by ninavizz** [comment]
Done as co-creation team exercise @ 2019 SD Offsite. Yet to collect documentation... @RyanRiceFPF might you have pix to share?

**Comment by RyanRiceFPF** [comment]
@ninavizz - i haven't had the time to transcribe yet, but here's the FPF Global Office - SecureDrop Retreat 2019 folder of pics - https://drive.google.com/drive/folders/1qBHmTrdkxJUPNy5L6dry14vXuGo_W2Fv

**Comment by ninavizz** [comment]
Closed as completed for above cited reasons. :)
