### ISSUE TITLE
Design Pilot Research

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-ux#23]
“To design an easy-to-use interface, pay attention to what users do, not only what they say. Self-reported claims are unreliable, as are user speculations about future behaviour.” (Jakob Nielsen – Alertbox)"

Pending the outcome of November's Workstation auditor review, in February 2019 we would like to deploy a set of provisioned/configured workstations to select customers. The goal of this pilot will be getting our completely new product into the wild, and learning from early users in advance of a general release. 

This ticket is to document ideas, needs, and sought outcomes, in preparation. 
This ticket is also less of a Story, and more of an evolving Epic. Gotta start somewhere. :)

**Open Questions**
• How should we vet/qualify Pilot participants?
• What value are we offering our participants, from this experience? 
• What value do we expect to deliver back into the product, in conclusion?
• How to best support Pilot users, while keeping a continuous feedback loop informing near and long term design and development needs?
• It is highly probably there will not be a full-time UX resource to manage the feedback-loop throughout the pilot. How to prepare for that, and how can the volunteer community contribute?

**Approach options**
• Diary studies? Video or written, analog or digital?
• Contextual inquiry—early or later? Of onboarding, or hold-off to mid-use? Both?

“User experience is not about how a product works on the inside. User experience is about how it works on the outside, where a person comes into contact with it and has to work with it” (J.J.Garrett – The Elements of User Experience).

**Comment by eloquence** [comment]
@ninavizz, @creviera and I had a first discussion about this today on the basis of this document Nina has prepared: [pilot research plan](https://docs.google.com/document/d/1pJwawILZjnyxBSKHFHa8abgDKMm-U_cqlXfYpeV9GR8/edit)

We reached high level agreement on the following points:

- We'll need to build an intake survey for pilot participants, to better understand current usage patterns.

- Before the pilot even starts, we may want to do some user tests of the current client with the participants. See: https://github.com/freedomofpress/securedrop-ux/issues/9#issuecomment-501493629

- During the pilot, we'd likely want to do a combination of scheduled interviews, plus a [diary study](https://www.nngroup.com/articles/diary-studies/), being very mindful of security considerations.

- See the document linked above for some of the questions we'd want to answer through those methods.

**Comment by ninavizz** [comment]
- [x] Intake survey created + deployed
- User tests pre-pilot w/ built client, not happening
- [ ] Diary study pages, in-progress
- [ ] Intake interviews to be scheduled
- [ ] Total research plan to be completed
- [ ] Discussion guide(s) yet to be done

**Comment by eloquence** [comment]
@ninavizz Could you update the status of this issue?

**Comment by ninavizz** [comment]
Absolutely! Just not within 30 days of the OG request. ;)
- Intake survey created and delivered
- Diary study on-hold, pending observation & incorporation into each org's Signal comms
- Baseline interviews completed for 1st org
- [Research plan](https://docs.google.com/document/d/1HveYPJa7HPZIqgPzNOfU4FZKvMAsOdFJi6Ey6k2yeb8/edit#) completed
- [Discussion guide](https://docs.google.com/document/d/1DoOGvp3Kz_Ph26GIH6mxm4eQoP0kmWzG5YGYM16LbLs/edit) for Baseline interviews completed
- Discussion guide for Topline interviews, will be drafted towards the end of the study once we have more insight into user things.
