### ISSUE TITLE
Complete November round of user testing

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-ux#24]
So far we have 4 confirmed participants for our November round of user testing. The plan of record is to test against the Invision Studio prototype, with likely focus on:

- timed interactions (e.g., progress indicators when downloading documents)
- improved export help (some problems with "wizard" in last test)
- message "snippets" in source view (can ask users about expectations)

**Comment by eloquence** [comment]
For the 11/28-12/12 sprint, we have two goals:
- do a round two with a tester who wasn't able to get through the whole prototype yet;
- reach out to a tester who indicated availability post-Thanksgiving.

Given the holiday period (and the fact that we have some major design, spec & prototyping work to do anyway), I suggest we skip additional sessions in December and continue with user testing in January -- but we may want to make an effort to at least line up testers for the new year.

**Comment by eloquence** [comment]
We finished all testing for November/December and are tracking insights from the tests in this synthesis spreadsheet:

https://docs.google.com/spreadsheets/d/1B7B8P9qEcOLT3IoBQS-6LEIb8jxTRNoFuSY1z_kyEbA/edit#gid=478630095

**Comment by ninavizz** [comment]
Testing summarized in more detail, with a link-out to the above spreadsheet, from this GitHub page:
https://github.com/freedomofpress/securedrop-ux/wiki/Qubes-Journalist-Workstation-Testing:-2nd-Round-(Q4-2018)
