### ISSUE TITLE
Files Download

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-ux#38]
### Problem
When a journalist clicks "Download" on a single file, or "Download All" for a batch of files... or, clicks "Download" on more than one individual file—what does that look like?

### Considerations
- This is mostly to get animations & progress bars created/spec'd; so... what do those look like?
- Are %% numbers quantified as a single-number countdown, or will it be coded to display batch progress w/in 3rds or 4ths?
- Where will these text indicators be, and where will the animated bars be?
- When there's a server-fail/hiccup, what will that look like?
  - When "Download All" is clicked and only a few file successfully download and others don't download at all—what does that look like?
  - If the connection is just doggy-dog slow, do we just stop? Do we let the user know and give them the option to continue or cancel?
  - Contextual help to explain Tor's specialness and likely network issues?

### Acceptance Criteria
- Clickable wireframe demonstrating interactivity 
- Play'able animation to demonstrate timed events & animations
- Anything else @creviera may need?
- Get on the needs testing punchlist

---
This is a sub-task within #18 and #31 and #17

**Comment by eloquence** [comment]
Pending:
- colors (part of larger visual design language work)
- text indicators of download stage (e.g., queue, downloading, decrypting)

**Comment by ninavizz** [comment]
First spec w/ choreography complete: zpl.io/beD5dzl

Should colors change, those changes will be indicated in #36
