### ISSUE TITLE
File Upload Messaging re: NoScript

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-ux#44]
## Problem
When a user seeks to upload a file today, often (usually when it's bigger than ~70mb) the upload will fail. It is not made clear to the user in the Source Interface, why. Now that we know why, we would like to instruct users how to work around this issue until it can be fixed.

## Considerations
- Workaround = NoScript Preferences > Advanced > Uncheck "Sanitize cross-site suspicious requests"
- Need to message users in the Source interface clearly but not alarmingly, how to do the above
- Messaging needs to be clear & obvious to users upon first visiting Upload functionality
  - Should not wait until a user's first upload fail to present info, as a user may be in a time-sensitive situation... and we don't want to create opportunities for a customer to NOT get important documents, because someone ran out of time.
- XXS Vulnerabilities a non-issue when JavaScript is disabled (which when Tor Slider is set to Most Secure, it is)

## Acceptance Critieria
- Clickable wireframes that people agree upon wrt interactivity
- Wireframes should include a few revs of messaging and be mostly accurate per Jen, John, and Erik
- Any cute new icons (more skullz?) should be included with Wireframes, on [parent ticket in SD Repo](https://github.com/freedomofpress/securedrop/issues/4078)
- Any screenshots or other artwork required for instructive click-thru, shd be included in parent ticket, too.

**Comment by ninavizz** [comment]
First jab at a solution. Mind the pink arrows at the top; a few things however, do navigate from w/in the wires. Would especially value feedback from @ei8fdb if available! :)

https://invis.io/9PQISNNBUMG#/346792367_As_Is

**Comment by ninavizz** [comment]
### Feedback/Discussion from UX Meeting 14 Feb 
- Nina's overview of the slides shown
  - See pink annotations at top of page
  - See arrows to navigate between pages
  - Design ideas progress from least-impact to highest-impact wrt text & styles changes
    - 2 basic directions presented: Ordered List vs Messaging Bubble
    - First slides cut-paste existing text verbatim, to preserve existing translations work
    - Further slides present recommended edits to reduce cognitive burden, ease UI test parsing
    - Furthest slides hide Encryption stuff behind a hidden Div; let the experts read that, don't intimidate non-GPG users with what is likely to promote imposter syndrome and potentially divert use to an insecure "but friendlier" medium.
  - Key Considerations between the two
    - Messaging bubble treatment obvs prioritizes urgency in a pleasing fashion; however, the "message" not going away when a user has changed their settings, is likely to be confusing. Tech realities vs user expectations.
    - Ordered List treatment is dependent on true (vs what we'd prefer) dependencies being shown in ordered priority.
      - The NoScript thing, first; the basic functionality offered by the tool, second; and how we'd like you to use it, third.
  - Additional things explored, tangential to NoScripts bug
    - **Blue cloud arrow icon:** Cloud semiotics, bad wrt implications for how data storage security does not work, with SD
      - Blue also suggests actionability, which this is not
      - Would like to replace with b/w SD logo, as users are putting things on an org's SecureDrop in this interaction
    - **Button Icons:** not necessary, visual noise, eliminate
    - **Body font:** Change font family to something more dense-text screen friendly than Helvetica Neu (which is my personal fav typeface, but it sucks for readability below header size). Google fonts are my personal fav library to pull from (and these mockups use Roboto, Montserrat, and Ariel), and open source—but @harrislapiroff flagged issues with Tor not even being able to use those families, when embedded, on the highest security setting? @kushal or @redshiftzero, any knowledge of this?
    - **Encryption:** Hide details in hidden Div; most Source users likely do not know what encryption is, or are not existing GPG users. Do we want to force Opsec 101 on this page, or calmly guide use of this page's functionality?
    - **Hide/Show Passcode:** Spiffier presentation; whole bar clickable, white-on-grey type treatment enhances accessibility with a low-contrast, while also making it more difficult for cameras to legibly capture information from afar

- Feedback
  - Everyone prefers Message bubble treatment, yet agrees with hypothesis it will confuse users by not being ephemeral
  - Ordered List version gets the green light
  - Body font too disruptive to change in such a quick fix release
  - Let's discuss the tangential tweaks (including what the default newsroom logo shipped with the product and included in documentation, is), in a future meeting?
  - Erik and Jen on the fence about swapping items 2 and 3. Nina feels strongly that ordering is more user-centered, as-is. John agrees with Nina. Who will win the bloody battle?

- Action Items
  - Nina to finish complete instructional page
  - Nina to cut-paste PNGs of page mockups into parent Issue in GH Repo
  - Nina to finalize text & cut-art for coding, and separately put into same GH issue

**Comment by ninavizz** [comment]
**Decided Upon Mockups (ignore the pink prototype nav arrows)**

![image](https://user-images.githubusercontent.com/8262612/52811127-30bdc600-3049-11e9-84ba-b66ac53c762c.png)


![image](https://user-images.githubusercontent.com/8262612/52811113-27345e00-3049-11e9-8fc9-e8364aa22791.png)

**Comment by ninavizz** [comment]
Good random feedback from @emkll on the progressive disclosure $.02 on Encryption (that is NOT a part of the NoScript messaging, but was proposed in these wires): Looks too much like a status indicator... like, it suggests "Encryption is on, click here to learn more!" Idea overall nice, but actionable button thingy needs to look less like a status indicator.

Nina's $.02: Ok, the GPG logo reduced that small just looks like a dang padlock. Whomp, whomp!

**Comment by ninavizz** [comment]
Ok... complete instructional page, and an additional hack on the confirmation message after a file has been uploaded (per feedback from @emkll). Click on links in wires to get to instructional page; pink arrows toggle between pages w/ and w/o confirmation message. 

Thoughts? https://projects.invisionapp.com/d/main#/console/16734520/346999529/preview

/cc @eloquence @redshiftzero @emkll

**Comment by eloquence** [comment]
Hey this looks great! The exact language for the I'll want to take a pass at tomorrow but overall this looks and feels right to me.

FWIW couple immediate small things:
- XSS not XXS
- I don't think it makes any difference for upload reliability whether you're on an .onion URL or not. The bug is going to bite during non-JavaScript web uploads (which are quite common on millions of webpages) intermittently if the box isn't checked.

**Comment by ninavizz** [comment]
Right... I just don't quite understand the difference between a "normal" website, and a .onion website, so am guessing most other non-techie types may not, either. :D

No time to gather evidence, so also creating my own fingernails-on-chalkboard noise by getting into the heads of users such as myself, to write what might make sense to non-techie types. If that makes sense. *sigh*

**Comment by ninavizz** [comment]
- Copy-edits made w/ @eloquence and doc is in OG issue
- Final art assets created, and [are located here](https://drive.google.com/open?id=16DUGdVwEZvQhOkPbIYFMJ8eWpcJHP6Q5)
- Final mockup (showing mostly final but not final-final copy)[ is here](https://drive.google.com/open?id=1i_ijYmjUg7sGrumZUOYnzCLQDThhjdGf)
