### ISSUE TITLE
Login Screen VisDe & IxD

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-ux#48]
Placeholder text to get Issue created for Login Screen VisDe & IxD.

- IxD greater priority ATM
- Needs to be reconsiled with how to do Online/Offline mode in desired fashion, which is very different from how Client is currently setup to work.
- Then, make it look proper

**Comment by eloquence** [comment]
Actionable:
- Hide client main window on launch
- Placeholder Qt active state for "Sign in" button, do not render main window until sign in fully complete to minimize lag
- Implement hyperlink to offline mode as shown in https://projects.invisionapp.com/share/72OJI1R8DTF#/screens/325169631
- Minimize text consistent with the above design

**Comment by ninavizz** [comment]
Done-y done! https://invis.io/J6RCFR4N5WM#/355922363_Desktop

Zeplin screens: https://app.zeplin.io/project/5c807ea562f734bd2756b243/dashboard?tag=Login

Final button color pending completion of #36
