### ISSUE TITLE
Co-Creation Source UI Workshop

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-ux#52]
Creating "Issue" to bookmark ongoing brainworm...

Would be very neat to assemble a small number of workshops in different locations... Portland, SF, Chicago, NYC. ??

Workshops would comprise of 2-3 FPF/Volunteer "SecureDrop" people. Attendees would be "Source Proxy" users—members of ACLU, labor unions, or others identified as possessing similar behavioral/values characteristics of Sources. 

Each participant would have the 4 primary Source screens to work with (get codename, login, submit, confirm), and bits of content to arrange on each screen as they'd see fit. They'd also have blank "content cards" to create their own content.

1. Attendees would be given the same use scenario
2. Attendees would be given their deck of screens/cards, and given 10min to order everything according to what is most important for them to see. 
3. Group Q&A session would ensue, and participants given the opportunity to re-arrange based on knew knowledge or provided clarification. 
4. Each participant would "present" their solution

**Comment by ninavizz** [comment]
Done as co-creation team exercise @ 2019 SD Offsite. Yet to collect documentation... @RyanRiceFPF might you have pix to share?

**Comment by RyanRiceFPF** [comment]
I thought I posted here this morning, I guess i didn't finalize -- @ninavizz here's the folder with all the SD retreat photos, I'm a bit behind in transcription https://drive.google.com/drive/folders/1qBHmTrdkxJUPNy5L6dry14vXuGo_W2Fv

**Comment by ninavizz** [comment]
Closing as this was completed with the 2019 offsite activities
