### ISSUE TITLE
Create newsroom survey for Journalist users

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-ux#58]
## Overview
Need to get journalists to commit 5-10 minutes for a proper survey to learn more about many things;
- Particulars that in less-sensitive need situations SD was created to do better than, reporting software such as Google Analytics could inform us about.
  -  FFR; ever, how often?
- Curiosities we need quant specificity around
  - See notes from David preso to UX meeting
  - See "Needs Testing" flag in UX repo
  - Nina/Erik/Jen have notes; ping Kev, too
- Wagtail has been used before, but I (nina) would prefer using a purpose-built survey tool.
  - Optimal Workshop, preferred tool
  - Surveymonkey or Google Survey, acceptable alternatives

Additionally, this Issue need not be held-up by #9, the drafting of a more holistic Research Plan for all Workstation things in preparation for the Pilot launch. We need data, we need it now—but these two tasks should happen in _parallel_, not series.

## Acceptance Criteria
- Survey is drafted in GDocs, iterated upon, and built.
- Letter drafted & prepared to send as Redmine blast, and then 1:1 to newsroom admins FPF peeps have established relationships with.
- FPF peeps not involved in creating survey, have successfully QA'd it.

**Comment by eloquence** [comment]
Current state of this ticket:
- We have a draft survey in Wagtail on securedrop.org (page ID `170` for those with access). The question set should be close to final at this point. The survey takes about 4 minutes to complete.
- Due to team PTO/sick time, we've not reviewed this together yet. The next UX meeting on Thursday may be a good opportunity for a cross-team test drive.
- @harrislapiroff has pushed a WIP implementation for form-related improvements. This will fix the "red banner" bug, and allow us to use images in survey questions (important for questions that relate to difficult to explain features, like "Flag for Reply"). https://github.com/freedomofpress/securedrop.org/pull/628 should be considered a blocker for survey launch.
- Nina and I still have a bit more work to do to flesh out the messaging and outreach plan for the survey.

**Comment by ninavizz** [comment]
## 13 Jun Review Notes
- Erik: Focus not necessarily Workstation, but to inform WS work
- Jen: Language around anonymization/plaintext in survey result sharing
- Olivia: Include `I have used this feature and I did not find it useful` as option?
- Olivia: Add options for `SMS`, `Voice call`, or `Other`
- Nina: put submit under many names to the top
- `What methods do you most often pursue when needing support/help?` As a question
- Nina: Time on task question?
- Jen: It would be useful to have q to probe into tools to work with post-submission on "What could help your workflow" probes?
- iMessage (apple)?
- Nina: Proton Mail? Answer: Meh, keep it at "Encrypted Email," _how_ peeps encrypt for interviews.
- Mickael: Do we have an idea of the size of the pool? Bigger pool = aggregate responses more secure.
- Erik: Training team has large network but it will be work to narrow that down to who's a SD user.

**Comment by eloquence** [comment]
First round of edits based on the above discussion are live:

- Added "I have tried feature but do not find it useful" bullet to relevant Qs
- Added "It would be useful to have better tools for working with files and documents" checkbox
- Added phone, SMS, iMessage, "Other" to comms methods
- Split out help/support related question
- Generalized "Can we follow up with you" question

Wording will still change as we validate against standard research methodologies.

**Comment by eloquence** [comment]
Also updated privacy language per earlier discussion. It now says:

> Survey responses are never shared with a third party. We will only share anonymized aggregate data publicly. Only the researcher and members of the Freedom of the Press Foundation staff will see your individual, detailed responses.

Added draft messaging to support portal members to our working GDoc:
https://docs.google.com/document/d/1TZYsKQw7dBbEMlaqcoLItr8ukUrW5hsV1ypXwlp014w/edit#

Tentatively targeting 6/20 for survey launch (a bit of of buffer after point release on 6/18, which will also result in a bulk announcement).

**Comment by ninavizz** [comment]
Took another spin through all the text & questions. 
### Survey Questions
See GDoc:
https://docs.google.com/document/d/1wKR7SOBci5wubqcDbdEJ0MQgDfJLUgdZi_bWP5y94to/edit?usp=sharing
### Intro Page:
- Update text, to below.
   - Current intro "Are you a...?" sounds too much like a late night TV infomercial introduction. :(
   - I've spent the morning reading a coupla book chapters and articles. From that I feel we should include a link to our last effort—while also reinforcing more the message of the value participation can offer. Showing users how we present results on the wiki can also help demonstrate just how we anonymize and aggregate data, to reassure them of safety.
- Update button text to say `Begin survey`

As such, my recommendation for the top blurb is the below, with "what we learned" linked-out to this: https://github.com/freedomofpress/securedrop-ux/wiki/Qubes-Journalist-Workstation-Testing:-2nd-Round-(Q4-2018)

```
If you are a person in your organization responsible for checking SecureDrop submissions, we need your help. The SecureDrop team wants to learn more about you and your unique needs so that we can serve those needs better with the tools we build. Our first such effort was conducted late last year, and what we learned was eye-opening and of great value.

This survey will only take 3-5 minutes to complete. At the end, we will also ask if you might be interested in participating in further research efforts, such as a phone interview or providing feedback on new ideas. 
```

**Comment by eloquence** [comment]
Nina and I have walked through these changes in detail, and applied most of them (as stated in the doc, or in slightly tweaked form) to the live version. Addition of screenshots is pending merge and deployment of https://github.com/freedomofpress/securedrop.org/pull/628.

**Comment by ninavizz** [comment]
## Screenshot Captions
### FFR
```
When looking at a source’s page, instead of the usual box for you to compose a
reply inside of there is the below button asking you to “flag this source for reply.”
```
### Change Codename
```
Link to the right of the source’s codename glued abnormality, says “Change codename.”
Clicking it will generate a new codename, and the same source will now have a new
random 2-word codename.
```
### Filter By Codename
```
Typing one of the words in a source’s codename into this box, will hide all sources
in the list below that do not have that word in their codename.
```
### Starring
```
tbd
```

**Comment by ninavizz** [comment]
### Updated Images
- [Starring](https://drive.google.com/open?id=1Qr3oNirNH0ftU5SLAooJJkiXgHQbq8jf)
- [FFR](https://drive.google.com/open?id=1KFF9MIowGXfI3mWKQC5cKImIYB9RqH3G)
- [Change codename](https://drive.google.com/open?id=1AcS1dePsKMQ9p_toHhEKZC55U0fr6p9J)
- [Filterable codename](https://drive.google.com/open?id=1ZwGUMgvUlmmS_aJOwoK29hEOf8qcIU0F)

**Comment by eloquence** [comment]
Survey was created, tested and launched (URL not being publicly advertised as we're targeting it directly to journalists/newsroom). Outreach is in progress and will be ongoing for the next few work days, tracked in #59.
