### ISSUE TITLE
Deploy/Engage Newsrooms for Survey

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-ux#59]
## Objectives
Upon the completion of #58 it will need to be deployed & responded to. People with FPF email accounts should be undertaking this outreach. Individuals familiar to Redmine users and folks with direct relationships with journalists, will be ideal. 

Keep in mind that Redmine can only be used to ask (already overworked) Admins to then do the work of engaging their Journalist users—and that 1:1 outreach directly to journalists, will be the more probable path to reap results from.

@eloquence can drive this ticket, but assistance from @zenmonkeykstop @harlo @olivemartini @huertanix @RyanRiceFPF and others will be requested, lauded, and bowed in reverence to.

## Acceptance Criteria
The survey should be live, with journalist and admins actively pursued by FPF peeps to engage, for at least 2 weeks. 

12 users would be my baseline-minimum, but I'd prefer to exceed that. This will be the first survey of its sort ever deployed, and getting 1/3 of all active journalist users to respond feels like a necessity to create the baseline knowledge we're seeking.

**Comment by eloquence** [comment]
First Redmine blast done on 6/20, 2 responses so far (but it's Friday). Will start on individual outreach next week, using contact lists that have been populated w/ training team help.

**Comment by eloquence** [comment]
We're at 10 responses currently, blocking time to send a few more pings tomorrow. Waiting with reminders to folks who've previously promised to respond until next week.

**Comment by ninavizz** [comment]
I'd like to leave the survey live for at least a few weeks. I've received 2 reminders for an IxDA local leaders survey I need to take, and that feels reasonable for a high-value survey of a small, targeted group of folks w/ specialized insight the general pop won't have.

**Comment by eloquence** [comment]
Another Redmine blast was sent yesterday, and the survey remains open until July 31. I'm not planning to send more bulk announcements, but additional individual outreach may still be warranted before we close it out.

We're currently at 16 total responses.

**Comment by eloquence** [comment]
Concluded with 17 respondents, evaluation of results to come.
