### ISSUE TITLE
Create user stories and acceptance criteria for beta client

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-ux#6]
In preparation for the beta version of the SecureDrop Workstation (most likely targeting end of February 2019), we should review the [SecureDrop Client User Stories](https://docs.google.com/spreadsheets/d/1DQEQp-0e6zN-pCPa0qqY-MGtmpc2SN5mzUsR4nEkpCQ/edit#gid=0) and turn them into well-specified issues, primarily in the [securedrop-client](https://github.com/freedomofpress/securedrop-client) repository. Each issue should have a user story, acceptance criteria (can follow Gherkin Given/When/Then syntax), and ideally a link to the relevant section of the latest clickable design, or a static screenshot.

Let's collaborate on this in a GDoc to begin with, to ensure we agree on the format (and can get initial sanity-check from the SecureDrop team), and then we can import into GitHub.

**Comment by eloquence** [comment]
This is currently WIP. The first issue filed as a result of this work is: 

https://github.com/freedomofpress/securedrop-client/issues/187

**Comment by eloquence** [comment]
For the 11/28-12/12 sprint, we're focusing on:
- iteration on download behavior
- iteration on open behavior
- status/notification messages

For specifying status/notification behavior, it'll be important that we have a preliminary agreement on the client's approach to concurrency and to resolving inconsistencies between client and server state resulting from incomplete pending operations on the server that have been optimistically completed on the client. (Architecture conversation on these topics to be scheduled.)

**Comment by ninavizz** [comment]
Closing, as I think we've accomplished this Issue's goals?

**Comment by eloquence** [comment]
We're not quite done here yet -- most client issues don't have clear acceptance criteria, and some are still very under-specified (export flow comes to mind) -- but we can file individual issues for that work to ensure we focus on the most important tasks, rather than one big "make everything better" epic. So fine with keeping this one closed.

**Comment by ninavizz** [comment]
^ Yep! Just trying to keep Issues here either clearly actionable w/in a few Sprints, or done as Epics. I could make this an Epic, tho. Maybe I should do that. Ok, I'll do that.

**Comment by ninavizz** [comment]
90% complete in spreadsheet at top of issue. Resolved as much as it needs to be.
