### ISSUE TITLE
[Source UxR] Draft Research Plan

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-ux#67]
_This is a child Issue within the epic #66_ 

## Problem
We need a plan to get this research going, man!

## Solution
A plan. 

Various needs discussed in [27 June UX meeting](https://github.com/freedomofpress/securedrop-ux/issues/65), and in a number of adhoc discussions. Those needs will be collected and considered upon this project's inclusion into a current sprint.

**Comment by ninavizz** [comment]
Draft—reviewed with Erik and Martin 17 July. https://docs.google.com/document/d/1Bdg8HqTfNI-0N1iZ2FhQA1inzZnZ0jPVCuJb9G3kHRQ/edit?usp=sharing

**Comment by eloquence** [comment]
Closing this as completed for purposes of a draft plan; next is the actual implementation in UserTesting.com or UserFeel.com.

**Comment by ninavizz** [comment]
Hay! We didn't finish it, as it never reached a state of completion... which is ok, because we're not there yet! Nope, it does not need to remain on the `bored` for this sprint.

**Comment by ninavizz** [comment]
E rik closed it, I shouldn't have re-opened. Less coffee, note to self.
