### ISSUE TITLE
Messages Downloading, Sync, and Fails: Deeper Dive

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-ux#70]
## Follow-up from Sprint UX Review 09 July:
Show: 
- Message not yet downloaded (skeleton pattern) in use case w/ many, many messages downloading
- Downloading 400 messages, and a timed sync is set to happen before the batch is done; how to reconsile?
- Message downloaded but failed to decrypt. Then what?
- Files and Messages all need to be downloading together—then what?

**Comment by creviera** [comment]
> Files and Messages all need to be downloading together—then what?

I don't think they do need to be downloaded together. We split the submissions into separate download jobs into separate queues.

**Comment by ninavizz** [comment]
^ @creviera Speaking purely from how user sees things, not at all wrt technical particulars on that one. Looking forward to hashing through technical particulars once scenarios are clearly defined for _how the user sees/experiences_ client operations... if that makes sense? 

eg: if the user has clicked "download" and then "sync," then from their perspective the two are happening together, regardless of how the queue is configured.

**Comment by ninavizz** [comment]
### Cut/Paste scenario blab from Nina's text-edit 

I'm starting the client
There's 300 Sources on the server
In the Metadata sync, my Client is told there are in fact 306 new Sources
Timestamp upon completion states "Last refresh: (when finished)"

**Comment by eloquence** [comment]
Since we're not likely to tackle this implementation in the next 1-2 sprints yet, we agreed to defer work on this for now.

**Comment by ninavizz** [comment]
Almost 2 years later, I'm pretty sure A l l i e re-did the queuing design. If I am mistaken, we can re-open this!
