### ISSUE TITLE
Design Tips/Landing Pages for New York World

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-ux#76]
_This Issue is a part of the Epic #66_ 

---

## Problem
For user testing sessions, we need a basic "starting point" from which users can get a sense for the context of using SecureDrop. Setting the stage for proxy source users to get a sense of needs and and motivations for actual sources using SecureDrop will be important. 

## Solution
Recreate both the WaPo's "Tips" and "Landing Page" for the fictional newsroom.

## Caveat(s)
- URL structures should reflect today's WaPo
- No live links on the Landing page
  - Q: Do they get the necessity to cut-and-paste?
 - We do not want users to download and install Tor
- Branding to reflect NY Daily World

**Comment by eloquence** [comment]
This was completed, and tested in a first trial run. Further improvements can be tracked separately.

**Comment by ninavizz** [comment]
Archived PNGs delivered for the above build showing what an "ideal" LP might resemble (per the fictional/historic newspaper NYWorld), below. In an ideal universe, it'd also be nice to build-out a few pages of the NYWorld website, to also show examples of ad-units placed in a site to solicit source contributions, and to show an example of a usable/tested all-platforms tips-page.

![NYWorld_2019LP](https://user-images.githubusercontent.com/8262612/96323623-c0600880-0fd2-11eb-8d1f-a25a7f2448b0.png)

![NYWorld_2019LP-HovBubs](https://user-images.githubusercontent.com/8262612/96323619-bb9b5480-0fd2-11eb-99b6-c208e08f8e93.png)
