### ISSUE TITLE
Prepare survey report and recommendations

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-ux#82]
Now that we have completed a SecureDrop User Survey, we want to prepare a high level, anonymized report, as well as some recommendations, e.g.:

- does the survey argue for removing any features (e.g., cycling codenames)?
- what methods for working with documents are important to support in the workstation?
- have any other issues been raised that we should give more attention to?

This issue should be considered resolved when a report has been completed and results have been shared at a UX meeting or similar team meeting.

**Comment by ninavizz** [comment]
Almost 2 years later, I'm pretty sure I reported-out on these findings. So, closing.
