### ISSUE TITLE
Print test page button

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-ux#85]
## Description
 There are 3 differnet methods available that relate to printing documents in the Export VM:
* `usb-test` (preflight without `disk-test` since we don't need to test a disk here)
* `printer-test`
* `printer`
(see https://github.com/freedomofpress/securedrop-export/#devices)

`printer-test` prints a test page and we currently don't have a place in the client for doing this.

**Comment by ninavizz** [comment]
I'm hesitant to prioritize this, as it feels like a very tangential feature. As the only power-user of `treeware` on the SD team, I've only ever printed a test page when looking for a network IP address or seeking to test the media of a printer. 

I'd rather we go into the Pilot w/o this feature, and to ask participants if they'd find it to be useful. Closing, for now, only to get it off the radar; entirely open to re-opening, if discussion merits, later on down the road.
