### ISSUE TITLE
Create updated research plan for continued Beta user research

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-ux#9]
• Present findings from existing research to team
• Solicit feedback on areas to delve into for continued research
• Open/unresolved things from the first plan?
• Questions to include to probe for Pilot participants?

**Comment by ninavizz** [comment]
Issue only relevant to research that will happen w/ in-progress VisualDesign implemented into prototype, no earlier than Q12019.

**Comment by eloquence** [comment]
Our goal for the 5/30-6/12 sprint is to:
- establish core research goals (e.g., validation of export workflow)
- identify near-term actions for the next 4 weeks

We'll also put together the user survey (#59) and @eloquence will do initial recruiting for remote research interviews.

**Comment by ninavizz** [comment]
To clarify: "Research goals" = what we want to learn, possibly why, and by when

**Comment by eloquence** [comment]
@ninavizz, @creviera and I discussed this today on the basis of this document that Nina has prepared: [pre-beta research plan](https://docs.google.com/document/d/13JuVu3LI2qAdAGxYd_kszhdgfrJowBrcFu_My6y5wII/edit)

Within this group, we agreed that the following approach could make sense:

- We should only be doing very limited remote testing of prototypes at this stage. Our main goal is to start getting feedback on the real client as soon as possible.

- This will require face-to-face testing, which is inherently resource intensive.

- As we already have to do face-to-face meetings with participants in the pilot anyway, it seems the most realistic to invite pilot participants to take part in a first set of user tests with the real client.

- To do this type of pre-beta testing, we'd need an alpha release that at least doesn't have showstopper issues that will reflect extremely poorly on the state of the client (e.g., data being lost, crashes, parts of the UI being extremely confusing). We should make an effort to identify all those issues. 

- Before showing the client to real newsrooms, we may also want to do some testing with FPF staff and friends of the organization (ideally not folks who are already very familiar with Qubes).

If that plan sounds reasonable, the immediate next step is for us to start building that list of showstopper issues. Note that missing functionality we want for beta is _not_ a "showstopper" in this sense -- it's fine to user-test a product that's unfinished in ways we can manage in a user test. But anything that fundamentally undermines people's confidence and trust would have to be addressed.

**Comment by eloquence** [comment]
We did in fact check in on this in the Monday client sync on 6/17, and agreed in principle to the above approach.

I've tentatively created this milestone:
https://github.com/freedomofpress/securedrop-client/milestone/4

which we can use for tracking showstopper issues that would prevent us from doing demos or  user research with pilot participants.

**Comment by eloquence** [comment]
Closing this out as original ticket goals are met; more work to come on research plan for the pilot group.
