### ISSUE TITLE
Login: Add troubleshooting tips info

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-ux#95]
# Description

Right now if you can't log into the client due to a timeout, you will see "There was a problem signing in. Please verify your credentials and try again."

We should have a different message for timeouts with network troubleshooting steps in a link.

**Comment by ninavizz** [comment]
Does that error show in the login window that sits atop the client VM window (two windows, same vm)?

**Comment by ninavizz** [comment]
WOO! Closed with #1258
